name: Cron Action
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'


jobs:
  amazonwishlist:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download artifact
        id: download
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cron.yml
          workflow_conclusion: success      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: pip install --upgrade pip -r requirements.txt
      - name: Run Rss to Telegram
        run: python example.py
        env:
          DESTINATION: ${{ secrets.DESTINATION }}
